INSERT INTO BIOSKOP(CIN_NAMA, CIN_LOKASI) VALUES ('XXI', 'KARAWACI');
SELECT * FROM BIOSKOP;

INSERT INTO STUDIO(CIN_ID, STD_KAPASITAS) VALUES ('CIN000001', 3);
SELECT * FROM STUDIO;

INSERT INTO KATEGORI_FILM(CAT_NAMA) VALUES ('SCIENCE FICTION');
SELECT * FROM KATEGORI_FILM;

INSERT INTO FILM(CAT_ID, MOV_JUDUL, MOV_DURASI) VALUES ('CAT000001', 'BIRD BOX', 120);
SELECT * FROM FILM;

INSERT INTO JADWAL(MOV_ID, STD_ID, SCH_WAKTU) VALUES ('MOV000001', 'STD000001', '2021-07-05');
SELECT * FROM JADWAL;

INSERT INTO PELANGGAN(PEL_NAMA, PEL_EMAIL, PEL_NO_TELEPON) VALUES('AKBAR', 'MUHRIZQULLAH@ICLOUD.COM', '0811111111');
SELECT * FROM PELANGGAN;

INSERT INTO METODE_PEMBAYARAN(PEL_ID, MTD_JENIS, MTD_BANK, MTD_NOMOR_KARTU, MTD_EXPIRED, MTD_CVV) 
VALUES('PEL000001', 'DEBIT', 'BNI', '1234567891234567', '0424', '392');
SELECT * FROM METODE_PEMBAYARAN;

INSERT INTO TRANSAKSI(PEL_ID, MTD_ID) VALUES('PEL000001', 'MTD000001');
SELECT * FROM TRANSAKSI;

INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('SCH000001', 'A01');
INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('SCH000001', 'A02');
INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('SCH000001', 'A03');
INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('SCH000001', 'A04');
INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('SCH000001', 'A05');
SELECT * FROM KURSI;