-- A Tiket yang dibeli
SELECT PELANGGAN.PEL_NAMA AS "Pelanggan", TRANSAKSI.TRX_ID AS "Nomor Transaksi", TIKET.TIK_ID AS "Nomor Tiket"
FROM PELANGGAN, TRANSAKSI, TIKET
WHERE PELANGGAN.PEL_ID = TRANSAKSI.PEL_ID AND TRANSAKSI.TRX_ID = TIKET.TRX_ID
AND PELANGGAN.PEL_ID = 'PEL000001';

-- C Jadwal yang tersedia dan filmnya
SELECT JADWAL.SCH_WAKTU as "Waktu", FILM.MOV_JUDUL as "Judul"
FROM JADWAL JOIN FILM ON JADWAL.MOV_ID=FILM.MOV_ID
WHERE SCH_WAKTU > CURRENT_TIMESTAMP;

-- Metode Pembayaran yg digunakan
SELECT PELANGGAN.PEL_NAMA AS "Pelanggan", METODE_PEMBAYARAN.MTD_JENIS AS "Jenis Kartu", METODE_PEMBAYARAN.MTD_BANK AS "Bank",  METODE_PEMBAYARAN.MTD_NOMOR_KARTU AS "Nomor Kartu"
FROM PELANGGAN JOIN METODE_PEMBAYARAN ON PELANGGAN.PEL_ID = METODE_PEMBAYARAN.PEL_ID
WHERE PELANGGAN.PEL_ID = 'PEL000008';
