INSERT INTO BIOSKOP(CIN_NAMA, CIN_LOKASI) VALUES ('XXI', 'KARAWACI');
SELECT * FROM BIOSKOP;

INSERT INTO STUDIO(CIN_ID, STD_KAPASITAS) VALUES ('0', 3);
SELECT * FROM STUDIO;

INSERT INTO KATEGORI_FILM(CAT_NAMA) VALUES ('SCIENCE FICTION');
SELECT * FROM KATEGORI_FILM;

INSERT INTO FILM(CAT_ID, MOV_JUDUL, MOV_DURASI) VALUES ('0', 'BIRD BOX', 120);
SELECT * FROM FILM;

INSERT INTO JADWAL(MOV_ID, STD_ID, SCH_WAKTU) VALUES ('0', '0', '2021-07-05');
SELECT * FROM JADWAL;

INSERT INTO PELANGGAN(PEL_NAMA, PEL_EMAIL, PEL_NO_TELEPON) VALUES('AKBAR', 'MUHRIZQULLAH@ICLOUD.COM', '0811111111');
SELECT * FROM PELANGGAN;

INSERT INTO METODE_PEMBAYARAN(PEL_ID, MTD_JENIS, MTD_BANK, MTD_NOMOR_KARTU, MTD_EXPIRED, MTD_CVV) 
VALUES('0', 'DEBIT', 'BNI', '1234567891234567', '0424', '392');
SELECT * FROM METODE_PEMBAYARAN;

INSERT INTO TRANSAKSI(PEL_ID, MTD_ID) VALUES('0', '0');
SELECT * FROM TRANSAKSI;

INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('0', 'A01');
INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('0', 'A02');
INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('0', 'A03');
SELECT * FROM KURSI;
--INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('0', 'A04');
--INSERT INTO KURSI(SCH_ID, CHR_KODE) VALUES('0', 'A05');

INSERT INTO VOUCHER(VOC_KODE_VOUCHER, VOC_NOMINAL) VALUES ('DISC10', 10000);
INSERT INTO VOUCHER(VOC_KODE_VOUCHER, VOC_NOMINAL) VALUES ('DISC5', 5000);
SELECT * FROM VOUCHER;

INSERT INTO Detail_Voucher(TRX_ID, VOC_ID) VALUES('0','0');
INSERT INTO Detail_Voucher(TRX_ID, VOC_ID) VALUES('0','1');
SELECT * FROM Detail_Voucher;

INSERT INTO TIKET(TRX_ID, CHR_ID)
VALUES ('0', '0');
INSERT INTO TIKET(TRX_ID, CHR_ID)
VALUES ('0', '1');
INSERT INTO TIKET(TRX_ID, CHR_ID)
VALUES ('0', '2');
SELECT * FROM TIKET;
--test

SELECT COUNT(TIK_ID) FROM TIKET WHERE TIKET.TRX_ID = 'TRX000001';

SELECT SUM(SCH_HARGA) FROM TIKET JOIN JADWAL ON TIKET.SCH_ID = JADWAL.SCH_ID
WHERE TIKET.TRX_ID = 'TRX000001';

SELECT SUM(VOC_NOMINAL)
FROM VOUCHER, TRANSAKSI, DetailVoucher
WHERE DetailVoucher.TRX_ID = TRANSAKSI.TRX_ID AND DetailVoucher.VOC_ID = VOUCHER.VOC_ID 
AND TRANSAKSI.TRX_ID='TRX000001';



SELECT SUM(SCH_HARGA) 
FROM TIKET, KURSI, JADWAL
WHERE TIKET.CHR_ID = KURSI.CHR_ID AND KURSI.SCH_ID = JADWAL.SCH_ID
AND TIKET.TRX_ID = '0'


SELECT ((SELECT SUM(SCH_HARGA) 
FROM TIKET, KURSI, JADWAL
WHERE TIKET.CHR_ID = KURSI.CHR_ID AND KURSI.SCH_ID = JADWAL.SCH_ID
AND TIKET.TRX_ID = '0') - (SELECT SUM(VOC_NOMINAL)
FROM VOUCHER, TRANSAKSI, DETAIL_VOUCHER
WHERE DETAIL_VOUCHER.TRX_ID = TRANSAKSI.TRX_ID AND DETAIL_VOUCHER.VOC_ID = VOUCHER.VOC_ID 
AND TRANSAKSI.TRX_ID='0'));