-- A Tiket yang dibeli
SELECT PELANGGAN.PEL_NAMA AS "Pelanggan", TRANSAKSI.TRX_ID AS "Nomor Transaksi", TIKET.TIK_ID AS "Nomor Tiket"
FROM PELANGGAN, TRANSAKSI, TIKET
WHERE PELANGGAN.PEL_ID = TRANSAKSI.PEL_ID AND TRANSAKSI.TRX_ID = TIKET.TRX_ID
AND PELANGGAN.PEL_ID = 'PEL000001';

-- C
SELECT JADWAL.SCH_WAKTU as "Waktu", FILM.MOV_JUDUL as "Judul"
FROM JADWAL JOIN FILM ON JADWAL.MOV_ID=FILM.MOV_ID
WHERE SCH_WAKTU > CURRENT_TIMESTAMP;